### ISSUE TITLE
add support for `checkout.Session.expire`

### ISSUE THREAD

**Issue by databasedav** [bhch/async-stripe#3]
[this](https://github.com/stripe/stripe-python/blob/master/stripe/api_resources/checkout/session.py#L11) was added [recently](https://github.com/stripe/stripe-python/releases/tag/v2.62.0)

**Comment by bhch** [comment]
Yeah, we are currently 5 versions behind the official stripe library. Seems a couple of days' work. I hope your requirement is not urgent.

**Comment by databasedav** [comment]
@bhch not at all, take your time, thanks :)

**Comment by bhch** [comment]
Added in [v2.62.0](https://github.com/bhch/async-stripe/releases/tag/v2.62.0). Please upgrade to the newest version.

I've also released v2.63.0 and now this lib is up-to-date with the official library.
